version: '3'
services: 
  db: 
    image: mysql:8
    container_name: mysql
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wpsait
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  wordpress:
    image: wordpress:5.2.4
    container_name: wordpress
    restart: always
    volumes: 
      - ./app/public/wp-content:/var/www/html/wp-content
    environment: 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wpsait
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
    ports:
      - 8080:80
      - 443:443
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 3333:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password